apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: go-github-actions-quay-060625 
  janus-idp.io/tekton: go-github-actions-quay-060625
  backstage.io/kubernetes-id: go-github-actions-quay-060625
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: go-github-actions-quay-060625
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml